# pipeline 依赖的 docker 镜像
image: node:latest

variables:
  IMAGE_NAME: lqshow/gilab-ci-nodejs
  CONTAINER_NAME: gilab-ci-nodejs
  PRODUCTION_VERSION: 0.0.1

services:
  - docker:dind

# 定义需要被缓存的文件、文件夹列表
cache:
  paths:
    - node_modules/

# 本次 pipeline 的 stages
stages:
 - install_deps
 - test
 - staging

# 安装依赖
install_deps:
  stage: install_deps
  only:
    - master
  script:
    - make install-deps
  retry: 2

# 运行测试
test:
  stage: test
  only:
    - master
  script:
   - make test
  retry: 2

# 部署测试服务器
deploy_to_staging:
  image: docker:latest
  stage: staging
  only:
    - master
  script:
    - apk upgrade --update && apk add bash make
    - make image-build
    - make deploy-to-staging