# pipeline 依赖的 docker 镜像
image: node:latest

variables:
  IMAGE_NAME: lqshow/gilab-ci-nodejs
  CONTAINER_NAME: gilab-ci-nodejs
  STAGING_VERSION: 0.0.1

# 定义需要被缓存的文件、文件夹列表
cache:
  paths:
    - node_modules/

# 本次 pipeline 的 stages
stages:
 - install_deps
 - test
 - staging

# 安装依赖
install_deps:
  stage: install_deps
  only:
    - master
  script:
    - npm install --unsafe-perm
  retry: 2

# 运行测试
test:
  stage: test
  only:
    - master
  script:
   - npm test
  retry: 2

# 部署测试服务器
deploy_to_staging:
  image: docker:latest
  stage: staging
  only:
    - master
  script:
    - pwd
    - ls -la
    - docker build -t "${IMAGE_NAME}":"${STAGING_VERSION}" .
    - docker stop "${CONTAINER_NAME}" && docker rm "${CONTAINER_NAME}"
    - docker run -d --name "${CONTAINER_NAME}" --restart always -p 10010:10010 --env NODE_ENV=test "${IMAGE_NAME}":"${STAGING_VERSION}"
